parameters:
    prodigious_sonata_menu.factory.class: Prodigious\Sonata\MenuBundle\Factory\MenuFactory
    prodigious_sonata_menu.manager.class: Prodigious\Sonata\MenuBundle\Manager\MenuManager
    prodigious_sonata_menu.repo.class: Prodigious\Sonata\MenuBundle\Repository\MenuRepository
    prodigious_sonata_menu_item.repo.class: Prodigious\Sonata\MenuBundle\Repository\MenuItemRepository
    prodigious_sonata_menu.admin.menu.controller.class: Prodigious\Sonata\MenuBundle\Controller\MenuController
    prodigious_sonata_menu.admin.menu_item.controller.class: Prodigious\Sonata\MenuBundle\Controller\MenuItemController

services:

    prodigious_sonata_menu.factory:
        class: '%prodigious_sonata_menu.factory.class%'

    prodigious_sonata_menu.manager:
        class: '%prodigious_sonata_menu.manager.class%'
        arguments: ["@doctrine.orm.entity_manager"]
        public: true

    prodigious_sonata_menu.repo:
        class: '%prodigious_sonata_menu.repo.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Prodigious\Sonata\MenuBundle\Model\MenuInterface
    
    prodigious_sonata_menu_item.repo:
        class: '%prodigious_sonata_menu_item.repo.class%'
        factory: ['@doctrine.orm.entity_manager', 'getRepository']
        arguments:
            - Prodigious\Sonata\MenuBundle\Model\MenuItemInterface
    
    prodigious_sonata_menu.admin.menu:
        class: '%sonata_menu.admins.menu%'
        arguments: [~, '%sonata_menu.entity.menu%', '%prodigious_sonata_menu.admin.menu.controller.class%']
        tags:
            - { name: sonata.admin, manager_type: orm, label: config.label_menu, group: config.label_menu, label_catalogue: ProdigiousSonataMenuBundle }
        calls:
            - [ setTranslationDomain, [ProdigiousSonataMenuBundle]]  
            - [ addChild, ['@prodigious_sonata_menu.admin.menu_item', 'menu']]
            
    prodigious_sonata_menu.admin.menu_item:
        class: '%sonata_menu.admins.menu_item%'
        arguments: [~, '%sonata_menu.entity.menu_item%', '%prodigious_sonata_menu.admin.menu_item.controller.class%', '%sonata_menu.entity.menu%']
        tags:
            - { name: sonata.admin, manager_type: orm, label: config.label_menu_item, group: config.label_menu, show_in_dashboard: false, label_catalogue: ProdigiousSonataMenuBundle }
        calls:
            - [ setTranslationDomain, [ProdigiousSonataMenuBundle]]
